### ISSUE TITLE
SonarQube 7.0 Post-Build

### ISSUE THREAD

**Issue by michelkaeser** [thienan93/phdiff#4]
Hi

Glad I came accross your plugin. Have been looking for such functionality for a while now.

One question: In SonarQube 7.0 there is no such thing as "Post Build Actions" nor do I see something similar to the screenshot. So is this plugin not compabitle and if not, any chance it will see an update soon?

Thanks!

**Comment by nthienan** [comment]
This plugin has not been tested with SonarQube 7.0 since the lasted version was 6.x when developing. Please share error log. In the meantime, I will check document of SonarQube 7.0

**Comment by michelkaeser** [comment]
I just tested and it still works great! Post build actions somehow seem to be taken up automatically.

One thing to mention is that the preview mode seems deprecated in SonarQube, but still works.
